### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by justinmann** [thomasgazzoni/react-native-keyboard-area#26]
The class is loaded from /Users/justinmann/.gradle/caches/transforms-3/1458f764e5f0be3b2595022fd3926dad/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/justinmann/Documents/GitHub/solito/node_modules/react-native-keyboard-area/android/src/main/java/com/rn/keyboard/RNKeyboardModule.kt: (48, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.1.

I am using "expo": "~47.0.12",

**Comment by justinmann** [comment]
This fixes it:
https://github.com/thomasgazzoni/react-native-keyboard-area/pull/27

**Comment by hantrungkien** [comment]
@thomasgazzoni could you please review PR and publish new version help me?

**Comment by thomasgazzoni** [comment]
@hantrungkien you can try now, I release a new version: 1.0.6
